# Generated by Django 4.2.9 on 2024-07-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpostcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='forumpostcategory',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='forumpostcategory',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='forumpostcategory',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='forumpostcategory',
            name='user',
        ),
        migrations.AddField(
            model_name='forumpostcategory',
            name='friendly_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
